// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNQXouZuoshANnIi5ry95kS5CEDM7xze0',
    appId: '1:43287869790:web:a3d315005f2b9e6bdc77cf',
    messagingSenderId: '43287869790',
    projectId: 'rush-alert-9e622',
    authDomain: 'rush-alert-9e622.firebaseapp.com',
    storageBucket: 'rush-alert-9e622.appspot.com',
    measurementId: 'G-VMK8RHEZSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC-WZ_seX2l9QxsVkEEErJ1KXR0rK76BA',
    appId: '1:43287869790:android:ea4c92e4a6cfb411dc77cf',
    messagingSenderId: '43287869790',
    projectId: 'rush-alert-9e622',
    storageBucket: 'rush-alert-9e622.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMqrZRyUEB8xKZFyOB25jOb4ktKs44bHM',
    appId: '1:43287869790:ios:028de2a31c289dbcdc77cf',
    messagingSenderId: '43287869790',
    projectId: 'rush-alert-9e622',
    storageBucket: 'rush-alert-9e622.appspot.com',
    iosBundleId: 'com.example.rushAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMqrZRyUEB8xKZFyOB25jOb4ktKs44bHM',
    appId: '1:43287869790:ios:6dcbecb0c5e80d33dc77cf',
    messagingSenderId: '43287869790',
    projectId: 'rush-alert-9e622',
    storageBucket: 'rush-alert-9e622.appspot.com',
    iosBundleId: 'com.example.rushAlert.RunnerTests',
  );
}
